object NagyTomegF: TNagyTomegF
  Left = 0
  Top = 0
  ClientHeight = 546
  ClientWidth = 1400
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  Position = poOwnerFormCenter
  WindowState = wsMaximized
  PixelsPerInch = 96
  TextHeight = 13
  object lblnagytomeg: TLabel
    AlignWithMargins = True
    Left = 3
    Top = 3
    Width = 1394
    Height = 540
    Align = alClient
    AutoSize = False
    BiDiMode = bdLeftToRight
    Caption = 'lblnagytomeg'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clRed
    Font.Height = -360
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBiDiMode = False
    ParentFont = False
    Layout = tlCenter
    OnClick = lblnagytomegClick
    ExplicitLeft = 267
    ExplicitTop = 19
  end
end
